name: vital_health_android
description: The Android implementation of Vital Health.
version: 4.5.3
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: vital_health
    platforms:
      android:
        package: io.vital.health
        pluginClass: VitalHealthPlugin
        dartPluginClass: VitalHealthAndroid

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  fimber: ^0.6.6
  vital_core:
    git:
      url: https://github.com/brancedev/vital-flutter.git
      ref: fastic_v1
      path: packages/vital_core/vital_core
  vital_health_platform_interface:
    git:
      url: https://github.com/brancedev/vital-flutter.git
      ref: fastic_v1
      path: packages/vital_health/vital_health_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  vital_core:
    git:
      url: https://github.com/brancedev/vital-flutter.git
      ref: fastic_v1
      path: packages/vital_core/vital_core
  vital_health_platform_interface:
    git:
      url: https://github.com/brancedev/vital-flutter.git
      ref: fastic_v1
      path: packages/vital_health/vital_health_platform_interface
